//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoFolderSyncServiceClient.FolderSyncService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolderStatus", Namespace="http://schemas.datacontract.org/2004/07/DemoWcfService1")]
    [System.SerializableAttribute()]
    public partial class FolderStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemCount {
            get {
                return this.ItemCountField;
            }
            set {
                if ((this.ItemCountField.Equals(value) != true)) {
                    this.ItemCountField = value;
                    this.RaisePropertyChanged("ItemCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileStatus", Namespace="http://schemas.datacontract.org/2004/07/DemoWcfService1")]
    [System.SerializableAttribute()]
    public partial class FileStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset CreateTimeUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTimeOffset LastModifiedUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset CreateTimeUtc {
            get {
                return this.CreateTimeUtcField;
            }
            set {
                if ((this.CreateTimeUtcField.Equals(value) != true)) {
                    this.CreateTimeUtcField = value;
                    this.RaisePropertyChanged("CreateTimeUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset LastModifiedUtc {
            get {
                return this.LastModifiedUtcField;
            }
            set {
                if ((this.LastModifiedUtcField.Equals(value) != true)) {
                    this.LastModifiedUtcField = value;
                    this.RaisePropertyChanged("LastModifiedUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FolderSyncService.IFolderSyncService")]
    public interface IFolderSyncService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderSyncService/Hello", ReplyAction="http://tempuri.org/IFolderSyncService/HelloResponse")]
        string Hello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderSyncService/Hello2", ReplyAction="http://tempuri.org/IFolderSyncService/Hello2Response")]
        string[] Hello2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderSyncService/Hello3", ReplyAction="http://tempuri.org/IFolderSyncService/Hello3Response")]
        DemoFolderSyncServiceClient.FolderSyncService.FolderStatus Hello3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderSyncService/GetFileStatus", ReplyAction="http://tempuri.org/IFolderSyncService/GetFileStatusResponse")]
        DemoFolderSyncServiceClient.FolderSyncService.FileStatus[] GetFileStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolderSyncService/Download", ReplyAction="http://tempuri.org/IFolderSyncService/DownloadResponse")]
        byte[] Download(string file, int begin, int size);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IFolderSyncServiceChannel : DemoFolderSyncServiceClient.FolderSyncService.IFolderSyncService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FolderSyncServiceClient : System.ServiceModel.ClientBase<DemoFolderSyncServiceClient.FolderSyncService.IFolderSyncService>, DemoFolderSyncServiceClient.FolderSyncService.IFolderSyncService {
        
        public FolderSyncServiceClient() {
        }
        
        public FolderSyncServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FolderSyncServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderSyncServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolderSyncServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello() {
            return base.Channel.Hello();
        }
        
        public string[] Hello2() {
            return base.Channel.Hello2();
        }
        
        public DemoFolderSyncServiceClient.FolderSyncService.FolderStatus Hello3() {
            return base.Channel.Hello3();
        }
        
        public DemoFolderSyncServiceClient.FolderSyncService.FileStatus[] GetFileStatus() {
            return base.Channel.GetFileStatus();
        }
        
        public byte[] Download(string file, int begin, int size) {
            return base.Channel.Download(file, begin, size);
        }
    }
}
